name: 'page'
version: 0.0.1
description: A wrapper for page.js
author: The Name It Later project authors
homepage: https://www.github.com/nameitlater/page

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0
  logging: ^0.11.0
  js: ^0.6.0
  dart_to_js_script_rewriter: ^0.1.0
  func: ^0.1.0

dev_dependencies:
  test: ^0.12.3
transformers:
  - polymer:
      entry_points:
        - example/index.html
  - $dart2js:
      minify: false
      commandLineOptions:
        - --trust-type-annotations
        - --trust-primitives
  - dart_to_js_script_rewriter
